language: generic

os:
  - linux
  - osx

env:
  - BUCKLESCRIPT=8

install:
  - npm install bs-platform@$BUCKLESCRIPT
  - npm install
  - npm list

script:
  - BISECT_ENABLE=yes npm run build
  - npm run test
  - npx bisect-ppx-report html
  - cat _coverage/index.html
  - npx bisect-ppx-report summary

notifications:
  email:
    on_success: always
    on_failure: always
